/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GalleryCategory = IDL.Variant({
  'activities' : IDL.Null,
  'results' : IDL.Null,
  'classroom' : IDL.Null,
});
export const ImageId = IDL.Nat;
export const Timestamp = IDL.Int;
export const GalleryImage = IDL.Record({
  'id' : ImageId,
  'title' : IDL.Text,
  'fileBlob' : ExternalBlob,
  'description' : IDL.Text,
  'category' : GalleryCategory,
  'uploadedAt' : Timestamp,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AssignmentId = IDL.Nat;
export const Assignment = IDL.Record({
  'id' : AssignmentId,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : IDL.Principal,
  'fileBlob' : IDL.Opt(ExternalBlob),
  'description' : IDL.Text,
  'deadline' : Timestamp,
});
export const ClassLevel = IDL.Variant({
  'class11to12' : IDL.Null,
  'class6to8' : IDL.Null,
  'class9to10' : IDL.Null,
});
export const StudentId = IDL.Nat;
export const Student = IDL.Record({
  'id' : StudentId,
  'principal' : IDL.Principal,
  'subjects' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'classLevel' : ClassLevel,
  'enrollmentDate' : Timestamp,
  'phone' : IDL.Text,
});
export const TestId = IDL.Nat;
export const ClassTest = IDL.Record({
  'id' : TestId,
  'totalMarks' : IDL.Nat,
  'subject' : IDL.Text,
  'testDate' : Timestamp,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
});
export const LeadId = IDL.Nat;
export const ResultId = IDL.Nat;
export const TestResult = IDL.Record({
  'id' : ResultId,
  'studentId' : StudentId,
  'marksObtained' : IDL.Nat,
  'feedback' : IDL.Opt(IDL.Text),
  'testId' : TestId,
});
export const AttendanceId = IDL.Nat;
export const AttendanceStatus = IDL.Variant({
  'present' : IDL.Null,
  'absent' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'id' : AttendanceId,
  'status' : AttendanceStatus,
  'studentId' : StudentId,
  'date' : IDL.Text,
  'markedBy' : IDL.Principal,
});
export const SubmissionId = IDL.Nat;
export const SubmissionStatus = IDL.Variant({
  'submitted' : IDL.Null,
  'late' : IDL.Null,
  'reviewed' : IDL.Null,
});
export const AssignmentSubmission = IDL.Record({
  'id' : SubmissionId,
  'status' : SubmissionStatus,
  'studentId' : StudentId,
  'fileBlob' : ExternalBlob,
  'submittedAt' : Timestamp,
  'assignmentId' : AssignmentId,
});
export const FollowUpStatus = IDL.Variant({
  'new' : IDL.Null,
  'enrolled' : IDL.Null,
  'contacted' : IDL.Null,
});
export const ChatbotLead = IDL.Record({
  'id' : LeadId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'preferredTime' : IDL.Text,
  'classInterest' : ClassLevel,
  'phone' : IDL.Text,
  'followUpStatus' : FollowUpStatus,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addGalleryImage' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, GalleryCategory],
      [GalleryImage],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAssignment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Timestamp, IDL.Opt(ExternalBlob)],
      [Assignment],
      [],
    ),
  'createStudent' : IDL.Func(
      [
        IDL.Principal,
        IDL.Text,
        ClassLevel,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
      ],
      [Student],
      [],
    ),
  'createTest' : IDL.Func(
      [IDL.Text, IDL.Text, Timestamp, IDL.Nat, IDL.Text],
      [ClassTest],
      [],
    ),
  'deactivateStudent' : IDL.Func([StudentId], [IDL.Bool], []),
  'deleteAssignment' : IDL.Func([AssignmentId], [IDL.Bool], []),
  'deleteGalleryImage' : IDL.Func([ImageId], [IDL.Bool], []),
  'deleteLead' : IDL.Func([LeadId], [IDL.Bool], []),
  'deleteTest' : IDL.Func([TestId], [IDL.Bool], []),
  'enterTestResult' : IDL.Func(
      [TestId, StudentId, IDL.Nat, IDL.Opt(IDL.Text)],
      [TestResult],
      [],
    ),
  'getAttendanceByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(Student)], ['query']),
  'getMySubmissions' : IDL.Func([], [IDL.Vec(AssignmentSubmission)], ['query']),
  'getMyTestResults' : IDL.Func([], [IDL.Vec(TestResult)], ['query']),
  'getResultsByTest' : IDL.Func([TestId], [IDL.Vec(TestResult)], ['query']),
  'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
  'getStudentAttendance' : IDL.Func(
      [StudentId],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getSubmissionsByAssignment' : IDL.Func(
      [AssignmentId],
      [IDL.Vec(AssignmentSubmission)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActiveStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'listAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
  'listGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'listGalleryImagesByCategory' : IDL.Func(
      [GalleryCategory],
      [IDL.Vec(GalleryImage)],
      ['query'],
    ),
  'listLeads' : IDL.Func([], [IDL.Vec(ChatbotLead)], ['query']),
  'listStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'listTests' : IDL.Func([], [IDL.Vec(ClassTest)], ['query']),
  'markAttendance' : IDL.Func(
      [StudentId, IDL.Text, AttendanceStatus],
      [AttendanceRecord],
      [],
    ),
  'submitAssignment' : IDL.Func(
      [AssignmentId, ExternalBlob],
      [AssignmentSubmission],
      [],
    ),
  'submitLead' : IDL.Func(
      [IDL.Text, IDL.Text, ClassLevel, IDL.Text],
      [ChatbotLead],
      [],
    ),
  'updateAttendance' : IDL.Func(
      [AttendanceId, AttendanceStatus],
      [IDL.Bool],
      [],
    ),
  'updateLeadStatus' : IDL.Func([LeadId, FollowUpStatus], [IDL.Bool], []),
  'updateStudent' : IDL.Func([Student], [IDL.Bool], []),
  'updateSubmissionStatus' : IDL.Func(
      [SubmissionId, SubmissionStatus],
      [IDL.Bool],
      [],
    ),
  'updateTestResult' : IDL.Func(
      [ResultId, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GalleryCategory = IDL.Variant({
    'activities' : IDL.Null,
    'results' : IDL.Null,
    'classroom' : IDL.Null,
  });
  const ImageId = IDL.Nat;
  const Timestamp = IDL.Int;
  const GalleryImage = IDL.Record({
    'id' : ImageId,
    'title' : IDL.Text,
    'fileBlob' : ExternalBlob,
    'description' : IDL.Text,
    'category' : GalleryCategory,
    'uploadedAt' : Timestamp,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AssignmentId = IDL.Nat;
  const Assignment = IDL.Record({
    'id' : AssignmentId,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : IDL.Principal,
    'fileBlob' : IDL.Opt(ExternalBlob),
    'description' : IDL.Text,
    'deadline' : Timestamp,
  });
  const ClassLevel = IDL.Variant({
    'class11to12' : IDL.Null,
    'class6to8' : IDL.Null,
    'class9to10' : IDL.Null,
  });
  const StudentId = IDL.Nat;
  const Student = IDL.Record({
    'id' : StudentId,
    'principal' : IDL.Principal,
    'subjects' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'classLevel' : ClassLevel,
    'enrollmentDate' : Timestamp,
    'phone' : IDL.Text,
  });
  const TestId = IDL.Nat;
  const ClassTest = IDL.Record({
    'id' : TestId,
    'totalMarks' : IDL.Nat,
    'subject' : IDL.Text,
    'testDate' : Timestamp,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
  });
  const LeadId = IDL.Nat;
  const ResultId = IDL.Nat;
  const TestResult = IDL.Record({
    'id' : ResultId,
    'studentId' : StudentId,
    'marksObtained' : IDL.Nat,
    'feedback' : IDL.Opt(IDL.Text),
    'testId' : TestId,
  });
  const AttendanceId = IDL.Nat;
  const AttendanceStatus = IDL.Variant({
    'present' : IDL.Null,
    'absent' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'id' : AttendanceId,
    'status' : AttendanceStatus,
    'studentId' : StudentId,
    'date' : IDL.Text,
    'markedBy' : IDL.Principal,
  });
  const SubmissionId = IDL.Nat;
  const SubmissionStatus = IDL.Variant({
    'submitted' : IDL.Null,
    'late' : IDL.Null,
    'reviewed' : IDL.Null,
  });
  const AssignmentSubmission = IDL.Record({
    'id' : SubmissionId,
    'status' : SubmissionStatus,
    'studentId' : StudentId,
    'fileBlob' : ExternalBlob,
    'submittedAt' : Timestamp,
    'assignmentId' : AssignmentId,
  });
  const FollowUpStatus = IDL.Variant({
    'new' : IDL.Null,
    'enrolled' : IDL.Null,
    'contacted' : IDL.Null,
  });
  const ChatbotLead = IDL.Record({
    'id' : LeadId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'preferredTime' : IDL.Text,
    'classInterest' : ClassLevel,
    'phone' : IDL.Text,
    'followUpStatus' : FollowUpStatus,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addGalleryImage' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, GalleryCategory],
        [GalleryImage],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAssignment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Timestamp, IDL.Opt(ExternalBlob)],
        [Assignment],
        [],
      ),
    'createStudent' : IDL.Func(
        [
          IDL.Principal,
          IDL.Text,
          ClassLevel,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
        ],
        [Student],
        [],
      ),
    'createTest' : IDL.Func(
        [IDL.Text, IDL.Text, Timestamp, IDL.Nat, IDL.Text],
        [ClassTest],
        [],
      ),
    'deactivateStudent' : IDL.Func([StudentId], [IDL.Bool], []),
    'deleteAssignment' : IDL.Func([AssignmentId], [IDL.Bool], []),
    'deleteGalleryImage' : IDL.Func([ImageId], [IDL.Bool], []),
    'deleteLead' : IDL.Func([LeadId], [IDL.Bool], []),
    'deleteTest' : IDL.Func([TestId], [IDL.Bool], []),
    'enterTestResult' : IDL.Func(
        [TestId, StudentId, IDL.Nat, IDL.Opt(IDL.Text)],
        [TestResult],
        [],
      ),
    'getAttendanceByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(Student)], ['query']),
    'getMySubmissions' : IDL.Func(
        [],
        [IDL.Vec(AssignmentSubmission)],
        ['query'],
      ),
    'getMyTestResults' : IDL.Func([], [IDL.Vec(TestResult)], ['query']),
    'getResultsByTest' : IDL.Func([TestId], [IDL.Vec(TestResult)], ['query']),
    'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
    'getStudentAttendance' : IDL.Func(
        [StudentId],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getSubmissionsByAssignment' : IDL.Func(
        [AssignmentId],
        [IDL.Vec(AssignmentSubmission)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActiveStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'listAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
    'listGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'listGalleryImagesByCategory' : IDL.Func(
        [GalleryCategory],
        [IDL.Vec(GalleryImage)],
        ['query'],
      ),
    'listLeads' : IDL.Func([], [IDL.Vec(ChatbotLead)], ['query']),
    'listStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'listTests' : IDL.Func([], [IDL.Vec(ClassTest)], ['query']),
    'markAttendance' : IDL.Func(
        [StudentId, IDL.Text, AttendanceStatus],
        [AttendanceRecord],
        [],
      ),
    'submitAssignment' : IDL.Func(
        [AssignmentId, ExternalBlob],
        [AssignmentSubmission],
        [],
      ),
    'submitLead' : IDL.Func(
        [IDL.Text, IDL.Text, ClassLevel, IDL.Text],
        [ChatbotLead],
        [],
      ),
    'updateAttendance' : IDL.Func(
        [AttendanceId, AttendanceStatus],
        [IDL.Bool],
        [],
      ),
    'updateLeadStatus' : IDL.Func([LeadId, FollowUpStatus], [IDL.Bool], []),
    'updateStudent' : IDL.Func([Student], [IDL.Bool], []),
    'updateSubmissionStatus' : IDL.Func(
        [SubmissionId, SubmissionStatus],
        [IDL.Bool],
        [],
      ),
    'updateTestResult' : IDL.Func(
        [ResultId, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };