/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assignment {
  'id' : AssignmentId,
  'title' : string,
  'subject' : string,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'fileBlob' : [] | [ExternalBlob],
  'description' : string,
  'deadline' : Timestamp,
}
export type AssignmentId = bigint;
export interface AssignmentSubmission {
  'id' : SubmissionId,
  'status' : SubmissionStatus,
  'studentId' : StudentId,
  'fileBlob' : ExternalBlob,
  'submittedAt' : Timestamp,
  'assignmentId' : AssignmentId,
}
export type AttendanceId = bigint;
export interface AttendanceRecord {
  'id' : AttendanceId,
  'status' : AttendanceStatus,
  'studentId' : StudentId,
  'date' : string,
  'markedBy' : Principal,
}
export type AttendanceStatus = { 'present' : null } |
  { 'absent' : null };
export interface ChatbotLead {
  'id' : LeadId,
  'name' : string,
  'createdAt' : Timestamp,
  'preferredTime' : string,
  'classInterest' : ClassLevel,
  'phone' : string,
  'followUpStatus' : FollowUpStatus,
}
export type ClassLevel = { 'class11to12' : null } |
  { 'class6to8' : null } |
  { 'class9to10' : null };
export interface ClassTest {
  'id' : TestId,
  'totalMarks' : bigint,
  'subject' : string,
  'testDate' : Timestamp,
  'name' : string,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'description' : string,
}
export type ExternalBlob = Uint8Array;
export type FollowUpStatus = { 'new' : null } |
  { 'enrolled' : null } |
  { 'contacted' : null };
export type GalleryCategory = { 'activities' : null } |
  { 'results' : null } |
  { 'classroom' : null };
export interface GalleryImage {
  'id' : ImageId,
  'title' : string,
  'fileBlob' : ExternalBlob,
  'description' : string,
  'category' : GalleryCategory,
  'uploadedAt' : Timestamp,
}
export type ImageId = bigint;
export type LeadId = bigint;
export type ResultId = bigint;
export interface Student {
  'id' : StudentId,
  'principal' : Principal,
  'subjects' : Array<string>,
  'name' : string,
  'isActive' : boolean,
  'email' : string,
  'classLevel' : ClassLevel,
  'enrollmentDate' : Timestamp,
  'phone' : string,
}
export type StudentId = bigint;
export type SubmissionId = bigint;
export type SubmissionStatus = { 'submitted' : null } |
  { 'late' : null } |
  { 'reviewed' : null };
export type TestId = bigint;
export interface TestResult {
  'id' : ResultId,
  'studentId' : StudentId,
  'marksObtained' : bigint,
  'feedback' : [] | [string],
  'testId' : TestId,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addGalleryImage' : ActorMethod<
    [string, string, ExternalBlob, GalleryCategory],
    GalleryImage
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAssignment' : ActorMethod<
    [string, string, string, Timestamp, [] | [ExternalBlob]],
    Assignment
  >,
  'createStudent' : ActorMethod<
    [Principal, string, ClassLevel, Array<string>, string, string],
    Student
  >,
  'createTest' : ActorMethod<
    [string, string, Timestamp, bigint, string],
    ClassTest
  >,
  'deactivateStudent' : ActorMethod<[StudentId], boolean>,
  'deleteAssignment' : ActorMethod<[AssignmentId], boolean>,
  'deleteGalleryImage' : ActorMethod<[ImageId], boolean>,
  'deleteLead' : ActorMethod<[LeadId], boolean>,
  'deleteTest' : ActorMethod<[TestId], boolean>,
  'enterTestResult' : ActorMethod<
    [TestId, StudentId, bigint, [] | [string]],
    TestResult
  >,
  'getAttendanceByDate' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyAttendance' : ActorMethod<[], Array<AttendanceRecord>>,
  'getMyProfile' : ActorMethod<[], [] | [Student]>,
  'getMySubmissions' : ActorMethod<[], Array<AssignmentSubmission>>,
  'getMyTestResults' : ActorMethod<[], Array<TestResult>>,
  'getResultsByTest' : ActorMethod<[TestId], Array<TestResult>>,
  'getStudent' : ActorMethod<[StudentId], [] | [Student]>,
  'getStudentAttendance' : ActorMethod<[StudentId], Array<AttendanceRecord>>,
  'getSubmissionsByAssignment' : ActorMethod<
    [AssignmentId],
    Array<AssignmentSubmission>
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listActiveStudents' : ActorMethod<[], Array<Student>>,
  'listAssignments' : ActorMethod<[], Array<Assignment>>,
  'listGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'listGalleryImagesByCategory' : ActorMethod<
    [GalleryCategory],
    Array<GalleryImage>
  >,
  'listLeads' : ActorMethod<[], Array<ChatbotLead>>,
  'listStudents' : ActorMethod<[], Array<Student>>,
  'listTests' : ActorMethod<[], Array<ClassTest>>,
  'markAttendance' : ActorMethod<
    [StudentId, string, AttendanceStatus],
    AttendanceRecord
  >,
  'submitAssignment' : ActorMethod<
    [AssignmentId, ExternalBlob],
    AssignmentSubmission
  >,
  'submitLead' : ActorMethod<[string, string, ClassLevel, string], ChatbotLead>,
  'updateAttendance' : ActorMethod<[AttendanceId, AttendanceStatus], boolean>,
  'updateLeadStatus' : ActorMethod<[LeadId, FollowUpStatus], boolean>,
  'updateStudent' : ActorMethod<[Student], boolean>,
  'updateSubmissionStatus' : ActorMethod<
    [SubmissionId, SubmissionStatus],
    boolean
  >,
  'updateTestResult' : ActorMethod<[ResultId, bigint, [] | [string]], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];