/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ClassTest {
    id: TestId;
    totalMarks: bigint;
    subject: string;
    testDate: Timestamp;
    name: string;
    createdAt: Timestamp;
    createdBy: Principal;
    description: string;
}
export type Timestamp = bigint;
export type LeadId = bigint;
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type TestId = bigint;
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type ResultId = bigint;
export type StudentId = bigint;
export type ImageId = bigint;
export interface TestResult {
    id: ResultId;
    studentId: StudentId;
    marksObtained: bigint;
    feedback?: string;
    testId: TestId;
}
export type SubmissionId = bigint;
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface GalleryImage {
    id: ImageId;
    title: string;
    fileBlob: ExternalBlob;
    description: string;
    category: GalleryCategory;
    uploadedAt: Timestamp;
}
export type AttendanceId = bigint;
export interface ChatbotLead {
    id: LeadId;
    name: string;
    createdAt: Timestamp;
    preferredTime: string;
    classInterest: ClassLevel;
    phone: string;
    followUpStatus: FollowUpStatus;
}
export interface AssignmentSubmission {
    id: SubmissionId;
    status: SubmissionStatus;
    studentId: StudentId;
    fileBlob: ExternalBlob;
    submittedAt: Timestamp;
    assignmentId: AssignmentId;
}
export type AssignmentId = bigint;
export interface Assignment {
    id: AssignmentId;
    title: string;
    subject: string;
    createdAt: Timestamp;
    createdBy: Principal;
    fileBlob?: ExternalBlob;
    description: string;
    deadline: Timestamp;
}
export interface AttendanceRecord {
    id: AttendanceId;
    status: AttendanceStatus;
    studentId: StudentId;
    date: string;
    markedBy: Principal;
}
export interface Student {
    id: StudentId;
    principal: Principal;
    subjects: Array<string>;
    name: string;
    isActive: boolean;
    email: string;
    classLevel: ClassLevel;
    enrollmentDate: Timestamp;
    phone: string;
}
export enum AttendanceStatus {
    present = "present",
    absent = "absent"
}
export enum ClassLevel {
    class11to12 = "class11to12",
    class6to8 = "class6to8",
    class9to10 = "class9to10"
}
export enum FollowUpStatus {
    new_ = "new",
    enrolled = "enrolled",
    contacted = "contacted"
}
export enum GalleryCategory {
    activities = "activities",
    results = "results",
    classroom = "classroom"
}
export enum SubmissionStatus {
    submitted = "submitted",
    late = "late",
    reviewed = "reviewed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addGalleryImage(title: string, description: string, fileBlob: ExternalBlob, category: GalleryCategory): Promise<GalleryImage>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAssignment(title: string, subject: string, description: string, deadline: Timestamp, fileBlob: ExternalBlob | null): Promise<Assignment>;
    createStudent(principal: Principal, name: string, classLevel: ClassLevel, subjects: Array<string>, phone: string, email: string): Promise<Student>;
    createTest(name: string, subject: string, testDate: Timestamp, totalMarks: bigint, description: string): Promise<ClassTest>;
    deactivateStudent(id: StudentId): Promise<boolean>;
    deleteAssignment(id: AssignmentId): Promise<boolean>;
    deleteGalleryImage(id: ImageId): Promise<boolean>;
    deleteLead(id: LeadId): Promise<boolean>;
    deleteTest(id: TestId): Promise<boolean>;
    enterTestResult(testId: TestId, studentId: StudentId, marksObtained: bigint, feedback: string | null): Promise<TestResult>;
    getAttendanceByDate(date: string): Promise<Array<AttendanceRecord>>;
    getCallerUserRole(): Promise<UserRole>;
    getMyAttendance(): Promise<Array<AttendanceRecord>>;
    getMyProfile(): Promise<Student | null>;
    getMySubmissions(): Promise<Array<AssignmentSubmission>>;
    getMyTestResults(): Promise<Array<TestResult>>;
    getResultsByTest(testId: TestId): Promise<Array<TestResult>>;
    getStudent(id: StudentId): Promise<Student | null>;
    getStudentAttendance(studentId: StudentId): Promise<Array<AttendanceRecord>>;
    getSubmissionsByAssignment(assignmentId: AssignmentId): Promise<Array<AssignmentSubmission>>;
    isCallerAdmin(): Promise<boolean>;
    listActiveStudents(): Promise<Array<Student>>;
    listAssignments(): Promise<Array<Assignment>>;
    listGalleryImages(): Promise<Array<GalleryImage>>;
    listGalleryImagesByCategory(category: GalleryCategory): Promise<Array<GalleryImage>>;
    listLeads(): Promise<Array<ChatbotLead>>;
    listStudents(): Promise<Array<Student>>;
    listTests(): Promise<Array<ClassTest>>;
    markAttendance(studentId: StudentId, date: string, status: AttendanceStatus): Promise<AttendanceRecord>;
    submitAssignment(assignmentId: AssignmentId, fileBlob: ExternalBlob): Promise<AssignmentSubmission>;
    submitLead(name: string, phone: string, classInterest: ClassLevel, preferredTime: string): Promise<ChatbotLead>;
    updateAttendance(id: AttendanceId, status: AttendanceStatus): Promise<boolean>;
    updateLeadStatus(id: LeadId, status: FollowUpStatus): Promise<boolean>;
    updateStudent(updated: Student): Promise<boolean>;
    updateSubmissionStatus(id: SubmissionId, status: SubmissionStatus): Promise<boolean>;
    updateTestResult(id: ResultId, marksObtained: bigint, feedback: string | null): Promise<boolean>;
}
import type { Assignment as _Assignment, AssignmentId as _AssignmentId, AssignmentSubmission as _AssignmentSubmission, AttendanceId as _AttendanceId, AttendanceRecord as _AttendanceRecord, AttendanceStatus as _AttendanceStatus, ChatbotLead as _ChatbotLead, ClassLevel as _ClassLevel, ExternalBlob as _ExternalBlob, FollowUpStatus as _FollowUpStatus, GalleryCategory as _GalleryCategory, GalleryImage as _GalleryImage, ImageId as _ImageId, LeadId as _LeadId, ResultId as _ResultId, Student as _Student, StudentId as _StudentId, SubmissionId as _SubmissionId, SubmissionStatus as _SubmissionStatus, TestId as _TestId, TestResult as _TestResult, Timestamp as _Timestamp, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addGalleryImage(arg0: string, arg1: string, arg2: ExternalBlob, arg3: GalleryCategory): Promise<GalleryImage> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryImage(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2), to_candid_GalleryCategory_n9(this._uploadFile, this._downloadFile, arg3));
                return from_candid_GalleryImage_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryImage(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2), to_candid_GalleryCategory_n9(this._uploadFile, this._downloadFile, arg3));
            return from_candid_GalleryImage_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAssignment(arg0: string, arg1: string, arg2: string, arg3: Timestamp, arg4: ExternalBlob | null): Promise<Assignment> {
        if (this.processError) {
            try {
                const result = await this.actor.createAssignment(arg0, arg1, arg2, arg3, await to_candid_opt_n18(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Assignment_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAssignment(arg0, arg1, arg2, arg3, await to_candid_opt_n18(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Assignment_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async createStudent(arg0: Principal, arg1: string, arg2: ClassLevel, arg3: Array<string>, arg4: string, arg5: string): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudent(arg0, arg1, to_candid_ClassLevel_n22(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
                return from_candid_Student_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudent(arg0, arg1, to_candid_ClassLevel_n22(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
            return from_candid_Student_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTest(arg0: string, arg1: string, arg2: Timestamp, arg3: bigint, arg4: string): Promise<ClassTest> {
        if (this.processError) {
            try {
                const result = await this.actor.createTest(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTest(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deactivateStudent(arg0: StudentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateStudent(arg0);
            return result;
        }
    }
    async deleteAssignment(arg0: AssignmentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAssignment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAssignment(arg0);
            return result;
        }
    }
    async deleteGalleryImage(arg0: ImageId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryImage(arg0);
            return result;
        }
    }
    async deleteLead(arg0: LeadId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLead(arg0);
            return result;
        }
    }
    async deleteTest(arg0: TestId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTest(arg0);
            return result;
        }
    }
    async enterTestResult(arg0: TestId, arg1: StudentId, arg2: bigint, arg3: string | null): Promise<TestResult> {
        if (this.processError) {
            try {
                const result = await this.actor.enterTestResult(arg0, arg1, arg2, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg3));
                return from_candid_TestResult_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enterTestResult(arg0, arg1, arg2, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg3));
            return from_candid_TestResult_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceByDate(arg0: string): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByDate(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByDate(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAttendance(): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAttendance();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAttendance();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySubmissions(): Promise<Array<AssignmentSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubmissions();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubmissions();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTestResults(): Promise<Array<TestResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTestResults();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTestResults();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResultsByTest(arg0: TestId): Promise<Array<TestResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResultsByTest(arg0);
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResultsByTest(arg0);
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudent(arg0: StudentId): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentAttendance(arg0: StudentId): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentAttendance(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentAttendance(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmissionsByAssignment(arg0: AssignmentId): Promise<Array<AssignmentSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionsByAssignment(arg0);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionsByAssignment(arg0);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listActiveStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActiveStudents();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActiveStudents();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAssignments(): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAssignments();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAssignments();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async listGalleryImages(): Promise<Array<GalleryImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGalleryImages();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGalleryImages();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async listGalleryImagesByCategory(arg0: GalleryCategory): Promise<Array<GalleryImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGalleryImagesByCategory(to_candid_GalleryCategory_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGalleryImagesByCategory(to_candid_GalleryCategory_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async listLeads(): Promise<Array<ChatbotLead>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLeads();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLeads();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async listStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudents();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudents();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTests(): Promise<Array<ClassTest>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTests();
            return result;
        }
    }
    async markAttendance(arg0: StudentId, arg1: string, arg2: AttendanceStatus): Promise<AttendanceRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.markAttendance(arg0, arg1, to_candid_AttendanceStatus_n54(this._uploadFile, this._downloadFile, arg2));
                return from_candid_AttendanceRecord_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAttendance(arg0, arg1, to_candid_AttendanceStatus_n54(this._uploadFile, this._downloadFile, arg2));
            return from_candid_AttendanceRecord_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitAssignment(arg0: AssignmentId, arg1: ExternalBlob): Promise<AssignmentSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAssignment(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_AssignmentSubmission_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAssignment(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_AssignmentSubmission_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitLead(arg0: string, arg1: string, arg2: ClassLevel, arg3: string): Promise<ChatbotLead> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLead(arg0, arg1, to_candid_ClassLevel_n22(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_ChatbotLead_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLead(arg0, arg1, to_candid_ClassLevel_n22(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_ChatbotLead_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAttendance(arg0: AttendanceId, arg1: AttendanceStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAttendance(arg0, to_candid_AttendanceStatus_n54(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAttendance(arg0, to_candid_AttendanceStatus_n54(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateLeadStatus(arg0: LeadId, arg1: FollowUpStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeadStatus(arg0, to_candid_FollowUpStatus_n56(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeadStatus(arg0, to_candid_FollowUpStatus_n56(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateStudent(arg0: Student): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(to_candid_Student_n58(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(to_candid_Student_n58(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSubmissionStatus(arg0: SubmissionId, arg1: SubmissionStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubmissionStatus(arg0, to_candid_SubmissionStatus_n60(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubmissionStatus(arg0, to_candid_SubmissionStatus_n60(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTestResult(arg0: ResultId, arg1: bigint, arg2: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTestResult(arg0, arg1, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTestResult(arg0, arg1, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
async function from_candid_AssignmentSubmission_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssignmentSubmission): Promise<AssignmentSubmission> {
    return await from_candid_record_n42(_uploadFile, _downloadFile, value);
}
async function from_candid_Assignment_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Assignment): Promise<Assignment> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceRecord_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceStatus): AttendanceStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_ChatbotLead_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatbotLead): ChatbotLead {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_ClassLevel_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClassLevel): ClassLevel {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FollowUpStatus_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FollowUpStatus): FollowUpStatus {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_GalleryCategory_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryCategory): GalleryCategory {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
async function from_candid_GalleryImage_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryImage): Promise<GalleryImage> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Student_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Student {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_SubmissionStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmissionStatus): SubmissionStatus {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_TestResult_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestResult): TestResult {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : from_candid_Student_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ImageId;
    title: string;
    fileBlob: _ExternalBlob;
    description: string;
    category: _GalleryCategory;
    uploadedAt: _Timestamp;
}): Promise<{
    id: ImageId;
    title: string;
    fileBlob: ExternalBlob;
    description: string;
    category: GalleryCategory;
    uploadedAt: Timestamp;
}> {
    return {
        id: value.id,
        title: value.title,
        fileBlob: await from_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.fileBlob),
        description: value.description,
        category: from_candid_GalleryCategory_n14(_uploadFile, _downloadFile, value.category),
        uploadedAt: value.uploadedAt
    };
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AssignmentId;
    title: string;
    subject: string;
    createdAt: _Timestamp;
    createdBy: Principal;
    fileBlob: [] | [_ExternalBlob];
    description: string;
    deadline: _Timestamp;
}): Promise<{
    id: AssignmentId;
    title: string;
    subject: string;
    createdAt: Timestamp;
    createdBy: Principal;
    fileBlob?: ExternalBlob;
    description: string;
    deadline: Timestamp;
}> {
    return {
        id: value.id,
        title: value.title,
        subject: value.subject,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        fileBlob: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.fileBlob)),
        description: value.description,
        deadline: value.deadline
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StudentId;
    principal: Principal;
    subjects: Array<string>;
    name: string;
    isActive: boolean;
    email: string;
    classLevel: _ClassLevel;
    enrollmentDate: _Timestamp;
    phone: string;
}): {
    id: StudentId;
    principal: Principal;
    subjects: Array<string>;
    name: string;
    isActive: boolean;
    email: string;
    classLevel: ClassLevel;
    enrollmentDate: Timestamp;
    phone: string;
} {
    return {
        id: value.id,
        principal: value.principal,
        subjects: value.subjects,
        name: value.name,
        isActive: value.isActive,
        email: value.email,
        classLevel: from_candid_ClassLevel_n26(_uploadFile, _downloadFile, value.classLevel),
        enrollmentDate: value.enrollmentDate,
        phone: value.phone
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ResultId;
    studentId: _StudentId;
    marksObtained: bigint;
    feedback: [] | [string];
    testId: _TestId;
}): {
    id: ResultId;
    studentId: StudentId;
    marksObtained: bigint;
    feedback?: string;
    testId: TestId;
} {
    return {
        id: value.id,
        studentId: value.studentId,
        marksObtained: value.marksObtained,
        feedback: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.feedback)),
        testId: value.testId
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AttendanceId;
    status: _AttendanceStatus;
    studentId: _StudentId;
    date: string;
    markedBy: Principal;
}): {
    id: AttendanceId;
    status: AttendanceStatus;
    studentId: StudentId;
    date: string;
    markedBy: Principal;
} {
    return {
        id: value.id,
        status: from_candid_AttendanceStatus_n35(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        date: value.date,
        markedBy: value.markedBy
    };
}
async function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SubmissionId;
    status: _SubmissionStatus;
    studentId: _StudentId;
    fileBlob: _ExternalBlob;
    submittedAt: _Timestamp;
    assignmentId: _AssignmentId;
}): Promise<{
    id: SubmissionId;
    status: SubmissionStatus;
    studentId: StudentId;
    fileBlob: ExternalBlob;
    submittedAt: Timestamp;
    assignmentId: AssignmentId;
}> {
    return {
        id: value.id,
        status: from_candid_SubmissionStatus_n43(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        fileBlob: await from_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.fileBlob),
        submittedAt: value.submittedAt,
        assignmentId: value.assignmentId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LeadId;
    name: string;
    createdAt: _Timestamp;
    preferredTime: string;
    classInterest: _ClassLevel;
    phone: string;
    followUpStatus: _FollowUpStatus;
}): {
    id: LeadId;
    name: string;
    createdAt: Timestamp;
    preferredTime: string;
    classInterest: ClassLevel;
    phone: string;
    followUpStatus: FollowUpStatus;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        preferredTime: value.preferredTime,
        classInterest: from_candid_ClassLevel_n26(_uploadFile, _downloadFile, value.classInterest),
        phone: value.phone,
        followUpStatus: from_candid_FollowUpStatus_n52(_uploadFile, _downloadFile, value.followUpStatus)
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    activities: null;
} | {
    results: null;
} | {
    classroom: null;
}): GalleryCategory {
    return "activities" in value ? GalleryCategory.activities : "results" in value ? GalleryCategory.results : "classroom" in value ? GalleryCategory.classroom : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    class11to12: null;
} | {
    class6to8: null;
} | {
    class9to10: null;
}): ClassLevel {
    return "class11to12" in value ? ClassLevel.class11to12 : "class6to8" in value ? ClassLevel.class6to8 : "class9to10" in value ? ClassLevel.class9to10 : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    present: null;
} | {
    absent: null;
}): AttendanceStatus {
    return "present" in value ? AttendanceStatus.present : "absent" in value ? AttendanceStatus.absent : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submitted: null;
} | {
    late: null;
} | {
    reviewed: null;
}): SubmissionStatus {
    return "submitted" in value ? SubmissionStatus.submitted : "late" in value ? SubmissionStatus.late : "reviewed" in value ? SubmissionStatus.reviewed : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    enrolled: null;
} | {
    contacted: null;
}): FollowUpStatus {
    return "new" in value ? FollowUpStatus.new : "enrolled" in value ? FollowUpStatus.enrolled : "contacted" in value ? FollowUpStatus.contacted : value;
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n33(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AssignmentSubmission>): Promise<Array<AssignmentSubmission>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AssignmentSubmission_n41(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TestResult>): Array<TestResult> {
    return value.map((x)=>from_candid_TestResult_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Student>): Array<Student> {
    return value.map((x)=>from_candid_Student_n24(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Assignment>): Promise<Array<Assignment>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Assignment_n19(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryImage>): Promise<Array<GalleryImage>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GalleryImage_n11(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatbotLead>): Array<ChatbotLead> {
    return value.map((x)=>from_candid_ChatbotLead_n50(_uploadFile, _downloadFile, x));
}
function to_candid_AttendanceStatus_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): _AttendanceStatus {
    return to_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function to_candid_ClassLevel_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassLevel): _ClassLevel {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FollowUpStatus_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FollowUpStatus): _FollowUpStatus {
    return to_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function to_candid_GalleryCategory_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GalleryCategory): _GalleryCategory {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Student_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Student): _Student {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_SubmissionStatus_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionStatus): _SubmissionStatus {
    return to_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: StudentId;
    principal: Principal;
    subjects: Array<string>;
    name: string;
    isActive: boolean;
    email: string;
    classLevel: ClassLevel;
    enrollmentDate: Timestamp;
    phone: string;
}): {
    id: _StudentId;
    principal: Principal;
    subjects: Array<string>;
    name: string;
    isActive: boolean;
    email: string;
    classLevel: _ClassLevel;
    enrollmentDate: _Timestamp;
    phone: string;
} {
    return {
        id: value.id,
        principal: value.principal,
        subjects: value.subjects,
        name: value.name,
        isActive: value.isActive,
        email: value.email,
        classLevel: to_candid_ClassLevel_n22(_uploadFile, _downloadFile, value.classLevel),
        enrollmentDate: value.enrollmentDate,
        phone: value.phone
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GalleryCategory): {
    activities: null;
} | {
    results: null;
} | {
    classroom: null;
} {
    return value == GalleryCategory.activities ? {
        activities: null
    } : value == GalleryCategory.results ? {
        results: null
    } : value == GalleryCategory.classroom ? {
        classroom: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassLevel): {
    class11to12: null;
} | {
    class6to8: null;
} | {
    class9to10: null;
} {
    return value == ClassLevel.class11to12 ? {
        class11to12: null
    } : value == ClassLevel.class6to8 ? {
        class6to8: null
    } : value == ClassLevel.class9to10 ? {
        class9to10: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): {
    present: null;
} | {
    absent: null;
} {
    return value == AttendanceStatus.present ? {
        present: null
    } : value == AttendanceStatus.absent ? {
        absent: null
    } : value;
}
function to_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FollowUpStatus): {
    new: null;
} | {
    enrolled: null;
} | {
    contacted: null;
} {
    return value == FollowUpStatus.new ? {
        new_: null
    } : value == FollowUpStatus.enrolled ? {
        enrolled: null
    } : value == FollowUpStatus.contacted ? {
        contacted: null
    } : value;
}
function to_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionStatus): {
    submitted: null;
} | {
    late: null;
} | {
    reviewed: null;
} {
    return value == SubmissionStatus.submitted ? {
        submitted: null
    } : value == SubmissionStatus.late ? {
        late: null
    } : value == SubmissionStatus.reviewed ? {
        reviewed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
